sudo: required

language: generic

services:
  - docker

before_install:
# Build Custom docker image for lunrjs and antora
  - echo "Building LUNR Docker Image"
  - docker build -t lunr/antora:custom -f Dockerfile.custom .
# Install Asciidoctor
#  - gem install asciidoctor
#  - asciidoctor --version
# Install Asciidoctor PDF and Requirements
#  - gem install asciidoctor-pdf --pre
#  - gem install rouge
#  - gem install pygments.rb
#  - gem install coderay
#  - asciidoctor-pdf --version
#  - npm i -g @antora/cli@2.1 @antora/site-generator-default@2.1
#  - npm install -g gitlab:antora/xref-validator


script:
#  - NODE_PATH="$(npm -g root)" antora --generator @antora/xref-validator suma-site.yml
  - echo "Building SUMA Antora Site"
  - docker run -u $UID --privileged -e DOCSEARCH_ENABLED=true -e DOCSEARCH_ENGINE=lunr -v $TRAVIS_BUILD_DIR:/antora/ --rm -t lunr/antora:custom suma-site.yml --generator antora-site-generator-lunr
  - ./travis.sh
#  - make pdf-all-suma
#  - make pdf-tar-suma
#  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc
#  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc

after_error:
  - docker logs antora-generator
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs antora-generator
  - docker logs asciidoc-to-pdf

after_success:
  - cd build ;
  - touch .nojekyll
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1


