sudo: required

language: generic

services:
  - docker

before_install:
  #- docker pull asciidoctor/docker-asciidoctor
  - docker build -t lunr-antora/antora .
  #- docker pull antora/antora:latest
  #- npm i antora-site-generator-lunr


script:
  - echo $TRAVIS_BUILD_DIR
  - docker run -u $UID --privileged -v $TRAVIS_BUILD_DIR:/antora/ --name antora-static-generator --rm -t lunr-antora/antora DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr suma-site.yml --generator ./node_modules/antora-site-generator-lunr
  - pwd
#  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc
#  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc
# --to-dir antora/output
#cp -R * ../output ; cd ../output ;

after_error:
  - docker logs antora-static-generator
#  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs antora-static-generator
#  - docker logs asciidoc-to-pdf

after_success:
  - ls -a build/
  - cd build ;
  - touch .nojekyll
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

#before_install:
#- git clone --depth 100 https://github.com/jcayouette/test-suma -b master
#  - git clone --depth 100 https://github.com/jcayouette/test-suma -b gh-pages
#  - cd test-suma/
# Get latest changes
#  - git fetch --all
#  - git pull -ff
# checkout gh page branch
#  - git checkout gh-pages
# remove content
#  - rm -rf suse-manager/ pdf/ _/ 404.html _headers index.html robots.txt search-index.js sitemap.xml susemanager-docs_en-pdf.tar.gz
#- git clone --depth 1 https://github.com/jcayouette/doc-susemanager-publisher
#- cd doc-susemanager-publisher
#  - docker pull antora/antora:latest
#  - docker run -v $TRAVIS_BUILD_DIR:/antora --rm -t antora/antora:latest --cache-dir=./.cache/antora suma-site.yml
#- cp -r public/uyuni/ia-rework-builder ../uyuni/
#- cp -r ./build/. ./
#- cd ../
#  - git pull
#  - git remote rm origin
#  - git remote add origin https://${GH_TOKEN}@github.com/jcayouette/test-suma -m gh-pages
#  - git fetch --all
#  - git pull -ff
#  - git add .
#  - git commit -am "New travis commit to gh-pages"
#  - git push --set-upstream origin gh-pages
