name: SUMA Build Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master 
      uses: actions/checkout@v1
    
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with: 
        ruby-version: 2.6.x
      
    - name: Build Lunr/Antora Custom Docker Image
      run: docker build -t lunr/antora:custom -f Dockerfile.custom .
    
    - name: Install Antora XREF Validator
      run: |
        npm i -g @antora/cli@2.1 @antora/site-generator-default@2.1
        npm install -g gitlab:antora/xref-validator
        
    - name: Validate XREFS (TEST)
      run: |
        NODE_PATH="$(npm -g root)" antora --generator @antora/xref-validator suma-site.yml
        
    
    - name: Build SUMA Docs with Lunr/Antora Custom Docker Image
      run: |
        docker run -u $UID --privileged -e DOCSEARCH_ENABLED=true -e DOCSEARCH_ENGINE=lunr -v $GITHUB_WORKSPACE:/antora/ --rm -t lunr/antora:custom suma-site.yml --generator antora-site-generator-lunr
        #cd build/
        ls -a
        
    - name: Install Asciidoctor and Asciidoctor PDF
      run: |
        gem install asciidoctor
        gem install asciidoctor-pdf --pre
        gem install rouge
        gem install pygments.rb
        gem install coderay
        asciidoctor --version
        asciidoctor-pdf --version
        
    - name: Build SUMA PDF Documents with Asciidoctor and Asciidoctor-pdf
      run: make pdf-all-suma
        
    - name: Create Tarball of all PDF Documents
      run: |
        make pdf-tar-suma
        ls -a build/
        ls -a build/pdf
        
    - name: Add no Jekyll
      run: touch build/.nojekyll
          
    - name: Deploy to GH-PAGES
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.        
      
