name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Lunr/Antora Docker image
      run: docker build -t lunr/antora:custom -f Dockerfile.custom .
